import React from "react";
import TermsImage from "../../assets/nenja-logo.png";
import { useNavigate } from "react-router-dom";

const Privacy = () => {
  const navigate = useNavigate();
  return (
    <div className="flex flex-col px-4 py-4">
      <div className="privacy-image">
        <img src={TermsImage} alt="Infiina Logo" className="w-[275px] cursor-pointer" onClick={() => navigate("/")} />
      </div>
      <h1 className="text-4xl font-bold text-[#1D3B6A]">Privacy Policy</h1>
      <div className="space-y-4 pb-2 text-[18px] text-black">
        <p className="text-[18px]">Last updated: January 01, 2024</p>
        <p className="text-[18px]">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="text-[18px]">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the Free Privacy Policy Generator.
        </p>
      </div>
      <div className="privacy-content">
        <div className="pb-2 text-3xl font-extrabold text-[#1D3B6A]">
          Interpretation and Definitions
        </div>
        <div className="pb-2 pt-1 text-[22px] font-semibold text-[#1D3B6A]">Interpretation</div>
        <div className="space-y-4 pb-2 text-base text-black">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </div>
        <div className="pb-2 pt-1 text-[22px] font-semibold text-[#1D3B6A]">Definitions</div>
        <div className="space-y-4 pb-2 text-base text-black">
          For the purposes of this Privacy Policy: <br />
          <ul>
            <li>
              <strong>Account </strong>means a unique account created for You to
              access our Service or parts of our Service.
            </li>

            <li>
              <strong>Company </strong>(referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to Infiina Artificial
              Intelligence, 123 Main St, New York, NY 10030.
            </li>
            <li>
              <strong>Cookies </strong>are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Country </strong>refers to: New York, United States
            </li>
            <li>
              <strong>Device </strong>means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data </strong>is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service </strong>refers to the Website.
            </li>
            <li>
              <strong>Service Provider </strong>means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Third-party Social Media Service </strong>refers to any
              website or any social network website through which a User can log
              in or create an account to use the Service.
            </li>
            <li>
              <strong>Usage Data </strong>refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
            <li>
              <strong>Website </strong>refers to Infiina, accessible from
              https://Infiina.ai
            </li>
            <li>
              <strong>You </strong>means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </div>

        <div className="pb-2 text-3xl font-extrabold text-[#1D3B6A]">
          Collecting and Using Your Personal Data{" "}
        </div>
        <div className="pb-2 pt-1 text-[22px] font-semibold text-[#1D3B6A]">Types of Data Collected</div>
        <div className="pb-2 pt-1 text-[22px] font-semibold text-[#1D3B6A]">Personal Data</div>
        <div className="space-y-4 pb-2 text-base text-black">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to: <br />
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>
        </div>
        <div className="pb-2 pt-1 text-[22px] font-semibold text-[#1D3B6A]">Usage Data</div>
        <div className="space-y-4 pb-2 text-base text-black">
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
